In [1]:
import numpy as np
from network import ShamirShare, merge_sum, interpolate

In [2]:
alice = ShamirShare(name="Alice", n=2, k=2, node_id=1)
bob = ShamirShare(name="Bob", n=2, k=2, node_id=2)
alice.create_shares(data=[1, 2, 3, 4, 5])
bob.create_shares(data=[6, 7, 8, 9, 10])
alice.shares, bob.shares

f
f


({'f': array([[ 398,  700,  673,  219,  974],
         [ 795, 1398, 1343,  434, 1943]])},
 {'f': array([[ 757,  328,  169, 1023, 1186],
         [1508,  649,  330, 2037, 2362]])})

In [4]:
alice_received_from_bob = bob.get_shares_for(node_id=1, share_type="f")
alice_received_from_bob

array([372, 972, 536, 348, 276])

In [5]:
alice.merge_shares(shares=alice_received_from_bob, by=merge_sum)
alice.shares

{'f': array([[  34,  398,  646,  998,  854],
        [  67,  794, 1289, 1992, 1703]]),
 'd': array([ 406, 1370, 1182, 1346, 1130])}

In [6]:
bob_received_from_alice = alice.get_shares_for(node_id=2, share_type="f")
bob_received_from_alice


array([  67,  794, 1289, 1992, 1703])

In [7]:
bob.merge_shares(shares=bob_received_from_alice, by=merge_sum)
bob.shares

{'f': array([[ 372,  972,  536,  348,  276],
        [ 738, 1937, 1064,  687,  542]]),
 'd': array([ 805, 2731, 2353, 2679, 2245])}

In [8]:
alice_d = alice.get_shares("d")
bob_d = bob.get_shares("d")
alice_d, bob_d


(array([ 406, 1370, 1182, 1346, 1130]), array([ 805, 2731, 2353, 2679, 2245]))

In [9]:
d = np.vstack((alice_d, bob_d)).T
d, d.T
# output

(array([[ 406,  805],
        [1370, 2731],
        [1182, 2353],
        [1346, 2679],
        [1130, 2245]]),
 array([[ 406, 1370, 1182, 1346, 1130],
        [ 805, 2731, 2353, 2679, 2245]]))

In [10]:
total = interpolate(d)
total

array([ 7.,  9., 11., 13., 15.])