In [1]:
from smpc_secrets import ShamirSecretSharing, AdditiveSecretSharing, Vandermonde, P

In [2]:
import numpy as np
from numpy.linalg import inv
from scipy.interpolate import lagrange

In [3]:
x = np.arange(1,4) # sum points indices 1, 2, 3
y = [132, 440, 930]       # sum points values s(1), s(2), s(3)
f = lagrange(x, y)
x, y, f

(array([1, 2, 3]), [132, 440, 930], poly1d([91., 35.,  6.]))

In [3]:
# Lagrange Interpolation for Addition section
def s(x):
    return 6+9*x+12*x**2
S=[s(x) for x in range(1,4)]
x = np.arange(1,4) # sum points indices 1, 2, 3
y = S       # sum points values s(1), s(2), s(3)
f = lagrange(x, y)
f, f(0), f(1), f(2), f(3)

(poly1d([12.,  9.,  6.]), 6.0, 27.0, 72.0, 141.0)

In [4]:
def additive(secret, n):
    additive_sharing = AdditiveSecretSharing(n=n)
    shares = additive_sharing.generate(s=secret)
    s = additive_sharing.reconstruct(shares=shares)
    print(f"secret: {secret}")
    print(f"shares: {shares}")
    print(f"reconstructed: {s}")

def shamir(secret, n, t):
    shamir = ShamirSecretSharing(n=n, t=t)
    shares = shamir.generate(s=secret)
    s = shamir.reconstruct(shares=shares)
    print(f"secret: {secret}")
    print(f"shares: {shares}")
    print(f"reconstructed: {s}")

def main():
    print("-------- Additive Secret Sharing ---------")
    additive(secret=22, n=5)

    print("\n-------- Shamir Secret Sharing ---------")
    shamir(secret=20, n=5, t=3)

In [5]:
main()

-------- Additive Secret Sharing ---------
secret: 22
shares: [(1, 183), (2, 1043), (3, 1220), (4, 490), (5, -2914)]
reconstructed: 22

-------- Shamir Secret Sharing ---------
secret: 20
shares: [(0, 20), (1, 1530), (2, 4272), (3, 8246), (4, 13452), (5, 19890)]
reconstructed: 20


In [6]:
shamir = ShamirSecretSharing(n=7, t=3)

In [7]:
def s(x):
    return 6 + 35*x+ 91*x**2+ 159*x**3+ 192*x**4+ 145*x**5+ 66*x**6

In [8]:
n=3
np.array([s(x) for x in range(1,n+1)])

array([   694,  13648, 104124])

In [9]:
# S=np.array([694,   13648,  104124])
S=np.array([s(x) for x in range(1,n+1)])
n = len(S)
B = np.array(Vandermonde(n))
Binv = inv(B)

In [10]:
t=1
S, B, Binv, P(n,t+1)

(array([   694,  13648, 104124]),
 array([[1, 1, 1],
        [1, 2, 4],
        [1, 3, 9]]),
 array([[ 3. , -3. ,  1. ],
        [-2.5,  4. , -1.5],
        [ 0.5, -1. ,  0.5]]),
 [[1, 0, 0], [0, 1, 0], [0, 0, 0]])

In [11]:
A = B @ P(n,t+1) @ Binv
R = A @ S
A, R

(array([[ 0.5,  1. , -0.5],
        [-2. ,  5. , -2. ],
        [-4.5,  9. , -3.5]]),
 array([ -38067., -141396., -244725.]))

In [12]:
# Lagrange Interpolation for Multiplication 
x = np.arange(1,len(R)+1) # prod points indices
y = R      # prod points values
f = lagrange(x, y)
x, y, f

(array([1, 2, 3]),
 array([ -38067., -141396., -244725.]),
 poly1d([-103329.,   65262.]))

In [13]:
f(0), f(1), f(2), f(3)

(65262.0, -38067.0, -141396.0, -244725.0)